import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { forkJoin, switchMap } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { CardModule } from 'primeng/card';
import { MessageModule } from 'primeng/message';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { TableModule } from 'primeng/table';
import { TagModule } from 'primeng/tag';
import { ConfirmationService, MessageService } from 'primeng/api';
import { ApiService } from '../../core/api.service';
import { Employee, EmploymentStatus, SalaryHistory } from '../../core/models';

@Component({
  selector: 'app-employee-detail',
  imports: [CommonModule, RouterLink, ButtonModule, CardModule, MessageModule, ProgressSpinnerModule, TableModule, TagModule],
  template: `
    @if (loading()) { <div class="loading-panel"><p-progressSpinner ariaLabel="Loading employee" /><span>Loading employee record…</span></div> }
    @else if (error()) { <p-message severity="error" [text]="error()!" /><a pButton routerLink="/employees" label="Back to employees" class="back-button"></a> }
    @else if (employee(); as person) {
      <header class="page-header"><div><a class="back-link" routerLink="/employees">← Back to employees</a><div class="person-heading"><span class="large-avatar">{{ initials(person) }}</span><div><p class="eyebrow">Employee profile</p><h1>{{ person.firstName }} {{ person.lastName }}</h1><p class="subtitle">{{ person.jobTitle }} · {{ person.employeeNumber }}</p></div></div></div><div class="header-actions"><a pButton [routerLink]="['/employees', person.id, 'edit']" label="Edit record" icon="pi pi-pencil" severity="secondary"></a><button pButton [label]="person.status === 'INACTIVE' ? 'Reactivate' : 'Deactivate'" [icon]="person.status === 'INACTIVE' ? 'pi pi-check' : 'pi pi-ban'" [severity]="person.status === 'INACTIVE' ? 'success' : 'danger'" (click)="changeStatus(person)"></button></div></header>
      <section class="profile-grid"><p-card header="Employee information"><dl><div><dt>Work email</dt><dd>{{ person.email }}</dd></div><div><dt>Department</dt><dd>{{ person.department }}</dd></div><div><dt>Location</dt><dd>{{ person.location }}, {{ person.country }}</dd></div><div><dt>Hire date</dt><dd>{{ person.hireDate | date:'mediumDate' }}</dd></div><div><dt>Employment status</dt><dd><p-tag [value]="statusLabel(person.status)" [severity]="statusSeverity(person.status)" /></dd></div><div><dt>Last updated</dt><dd>{{ person.updatedAt | date:'medium' }}</dd></div></dl></p-card><p-card header="Current compensation"><div class="compensation-total"><span>Total compensation</span><strong>{{ person.currency }} {{ person.totalCompensation | number:'1.0-0' }}</strong><small>Annual · {{ person.currency }}</small></div><div class="comp-row"><span>Base salary</span><strong>{{ person.currency }} {{ person.baseSalary | number:'1.0-0' }}</strong></div><div class="comp-row"><span>Annual bonus</span><strong>{{ person.currency }} {{ person.bonus | number:'1.0-0' }}</strong></div></p-card></section>
      <section class="history-card"><div class="section-heading"><div><h2>Salary history</h2><p>Compensation snapshots are retained whenever salary changes.</p></div></div><p-table [value]="history()" [tableStyle]="{'min-width':'45rem'}"><ng-template #header><tr><th>Effective date</th><th>Base salary</th><th>Bonus</th><th>Total</th><th>Reason</th></tr></ng-template><ng-template #body let-record><tr><td>{{ record.effectiveDate | date:'mediumDate' }}</td><td>{{ record.currency }} {{ record.baseSalary | number:'1.0-0' }}</td><td>{{ record.currency }} {{ record.bonus | number:'1.0-0' }}</td><td><strong>{{ record.currency }} {{ record.totalCompensation | number:'1.0-0' }}</strong></td><td>{{ record.changeReason }}</td></tr></ng-template><ng-template #emptymessage><tr><td colspan="5">No salary history available.</td></tr></ng-template></p-table></section>
    }
  `,
  styles: [`.page-header{align-items:flex-end;display:flex;justify-content:space-between;margin-bottom:2rem}.back-link{color:#486581;display:block;font-size:.8rem;margin-bottom:1.3rem;text-decoration:none}.person-heading{align-items:center;display:flex;gap:.9rem}.eyebrow{color:#2f855a;font-size:.72rem;font-weight:800;letter-spacing:.1em;margin:0 0 .35rem;text-transform:uppercase}h1{color:#102a43;font-size:2rem;letter-spacing:-.04em;margin:0}.subtitle{color:#627d98;margin:.4rem 0 0}.large-avatar{align-items:center;background:#e6fffa;border-radius:14px;color:#16846d;display:inline-flex;font-size:1.3rem;font-weight:800;height:62px;justify-content:center;width:62px}.header-actions{display:flex;gap:.7rem}.profile-grid{display:grid;gap:1.25rem;grid-template-columns:1.2fr .8fr}.profile-grid dl{display:grid;gap:1rem;grid-template-columns:1fr 1fr;margin:0}.profile-grid dl div{border-bottom:1px solid #edf2f7;padding-bottom:.75rem}.profile-grid dt{color:#829ab1;font-size:.7rem;font-weight:700;margin-bottom:.3rem}.profile-grid dd{color:#334e68;font-size:.85rem;margin:0}.compensation-total{border-bottom:1px solid #edf2f7;padding-bottom:1.25rem}.compensation-total span,.compensation-total small{color:#829ab1;display:block;font-size:.76rem}.compensation-total strong{color:#102a43;display:block;font-size:1.65rem;margin:.3rem 0}.comp-row{display:flex;justify-content:space-between;padding-top:1rem}.comp-row span{color:#627d98;font-size:.82rem}.comp-row strong{color:#334e68;font-size:.83rem}.history-card{background:#fff;border:1px solid #e6edf3;border-radius:12px;margin-top:1.25rem;overflow:hidden}.section-heading{padding:1.2rem 1.25rem .5rem}.section-heading h2{color:#243b53;font-size:1rem;margin:0}.section-heading p{color:#829ab1;font-size:.75rem;margin:.35rem 0 0}.history-card p-table{display:block;padding:.5rem 1rem 1rem}.loading-panel{align-items:center;background:#fff;border-radius:12px;display:flex;flex-direction:column;gap:.8rem;justify-content:center;min-height:250px}.back-button{display:inline-flex;margin-top:1rem}@media(max-width:720px){.page-header{align-items:stretch;flex-direction:column;gap:1rem}.header-actions{flex-wrap:wrap}.profile-grid{grid-template-columns:1fr}.profile-grid dl{grid-template-columns:1fr}}`]
})
export class EmployeeDetailComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly api = inject(ApiService);
  private readonly confirmation = inject(ConfirmationService);
  private readonly messages = inject(MessageService);
  readonly loading = signal(true); readonly error = signal<string | null>(null); readonly employee = signal<Employee | null>(null); readonly history = signal<SalaryHistory[]>([]);
  ngOnInit(): void { this.load(); }
  load(): void { this.loading.set(true); this.route.paramMap.pipe(switchMap(params => forkJoin({ employee: this.api.employee(params.get('id')!), history: this.api.salaryHistory(params.get('id')!) }))).subscribe({ next: result => { this.employee.set(result.employee); this.history.set(result.history); this.loading.set(false); }, error: () => { this.error.set('This employee could not be loaded. The record may no longer exist.'); this.loading.set(false); } }); }
  changeStatus(person: Employee): void { const nextStatus: EmploymentStatus = person.status === 'INACTIVE' ? 'ACTIVE' : 'INACTIVE'; this.confirmation.confirm({ header: nextStatus === 'INACTIVE' ? 'Deactivate employee?' : 'Reactivate employee?', message: nextStatus === 'INACTIVE' ? 'The record will be retained but excluded from active workforce metrics.' : 'This employee will be included in active workforce metrics again.', icon: 'pi pi-exclamation-triangle', acceptLabel: nextStatus === 'INACTIVE' ? 'Deactivate' : 'Reactivate', rejectLabel: 'Cancel', accept: () => this.api.updateStatus(person.id, nextStatus).subscribe({ next: updated => { this.employee.set(updated); this.messages.add({ severity: 'success', summary: 'Status updated', detail: `${updated.firstName} is now ${this.statusLabel(updated.status).toLowerCase()}.` }); }, error: () => this.messages.add({ severity: 'error', summary: 'Update failed', detail: 'The employee status could not be changed.' }) }) }); }
  initials(person: Employee): string { return `${person.firstName[0]}${person.lastName[0]}`.toUpperCase(); }
  statusLabel(status: EmploymentStatus): string { return status === 'ON_LEAVE' ? 'On leave' : status[0] + status.slice(1).toLowerCase(); }
  statusSeverity(status: EmploymentStatus): 'success' | 'warn' | 'danger' { return status === 'ACTIVE' ? 'success' : status === 'ON_LEAVE' ? 'warn' : 'danger'; }
}
